apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
  annotations:
    openshift.io/display-name: vLLM ServingRuntime for KServe
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    openshift.io/display-name: vLLM ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: 'true'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Name}}'
        - '--dtype=float16'
        - '--enforce-eager'
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: VLLM_CACHE_ROOT
          value: /tmp/
      image: 'quay.io/modh/vllm@sha256:4b9dd97838cf5f4b2c9dde0357abef2a7953965f028a07446e78f2a412df90fb'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen25
  labels:
    opendatahub.io/dashboard: 'true'
    #networking.kserve.io/visibility: exposed
  annotations:
    openshift.io/display-name: qwen25
    serving.knative.openshift.io/enablePassthrough: 'true'
    security.opendatahub.io/enable-auth: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    haproxy.router.openshift.io/timeout: 600s
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 10Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: vllm-runtime
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog@sha256:b96bd7aac6d2d6d0ec86166037e68fdff31152588846ffbd9e8fc41dd571b9e8
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists